const css = require('./css')

module.exports = function (outgoingResponse) {
    outgoingResponse.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'})
    outgoingResponse.write('<!DOCTYPE html>')
    outgoingResponse.write('<meta name="viewport" content="width=device-width, initial-scale=1.0" />')
    outgoingResponse.write('<title>Sheet</title>')
    outgoingResponse.write(`<style>${css()}</style>`)
    outgoingResponse.write('<div><a href="/w/n">Järfälla norrut</a></div>')
    outgoingResponse.write('<div><a href="/w/s">Järfälla söderut</a></div>')
    outgoingResponse.write('<div><a href="/n/n">Solna norrut</a></div>')
    outgoingResponse.write('<div><a href="/n/s">Solna söderut</a></div>')
    outgoingResponse.write('<div><a href="/c/n">Centralen norrut</a></div>')
    outgoingResponse.write('<div><a href="/c/s">Centralen söderut</a></div>')
    outgoingResponse.write('<div><a href="/s/n">Huddinge norrut</a></div>')
    outgoingResponse.write('<div><a href="/s/s">Huddinge söderut</a></div>')
    outgoingResponse.write('<div><a href="/e/n">Haninge norrut</a></div>')
    outgoingResponse.write('<div><a href="/e/s">Haninge söderut</a></div>')
    outgoingResponse.end()
}
